#### 2015-08-27 17:45:55,117 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 17:58:17,672 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 17:58:30,903 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 18:12:28,762 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 18:22:13,778 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 18:22:15,962 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 18:39:48,554 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 18:39:53,744 ==> INFO: Starting up... [in run.py:21]
#### 2015-08-27 18:46:22,528 ==> ERROR: An exception occurred trying to send '{rec.foto}' from 'photos'. Does the file exist? [in views.py:178]
#### 2015-08-27 18:46:58,032 ==> ERROR: An exception occurred trying to send '{rec.foto}' from 'photos'. Does the file exist? [in views.py:178]
#### 2015-08-27 18:47:31,274 ==> INFO: Switching off.. [in run.py:32]
################
